Webbshop/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Webbshop.Data;
using Webbshop.Models;

namespace Webbshop.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IHttpContextAccessor httpContextAccessor;

        public CheckoutModel(AppDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            this.httpContextAccessor = httpContextAccessor;
        }

        public Basket basket { get; set; }
        public List<Product> SelectedProducts { get; set; } = new List<Product>();

        public async Task OnGetAsync()
        {
            var accessControl = new AccessControl(_context, httpContextAccessor);
            var accId = accessControl.GetLoggedInAccountId();

            basket = await _context.Baskets.Include(b => b.Items).FirstOrDefaultAsync(b => b.AccountId == accId);

            if (basket != null && basket.NumberOfItems > 0)
            {
                var productIds = basket.Items.Select(item => item.ProductId).ToList();
                SelectedProducts = await _context.Products.Where(p => productIds.Contains(p.Id)).ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostRemoveProductAsync(int itemId)
        {
            var accessControl = new AccessControl(_context, httpContextAccessor);
            var accId = accessControl.GetLoggedInAccountId();

            var basket = await _context.Baskets
                .Include(b => b.Items)
                .FirstOrDefaultAsync(b => b.AccountId == accId);

            if (basket != null)
            {
                var itemToRemove = basket.Items.FirstOrDefault(item => item.Id == itemId);
                if (itemToRemove != null)
                {
                    _context.Remove(itemToRemove);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToPage("/Checkout");
        }

        public async Task<IActionResult> OnPostRemoveAllItemsAsync()
        {
            var accessControl = new AccessControl(_context, httpContextAccessor);
            var accId = accessControl.GetLoggedInAccountId();

            var basket = await _context.Baskets
                .Include(b => b.Items)
                .FirstOrDefaultAsync(b => b.AccountId == accId);

            if (basket != null)
            {
                _context.RemoveRange(basket.Items); 
                await _context.SaveChangesAsync(); 
            }

            return RedirectToPage("/Checkout");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var accessControl = new AccessControl(_context, httpContextAccessor);
            var accId = accessControl.GetLoggedInAccountId();

            basket = await _context.Baskets.Include(b => b.Items).FirstOrDefaultAsync(b => b.AccountId == accId);

            if (ModelState.IsValid)
            {
                    var totalCostCheckout = basket.Items.Sum(p => p.Quantity * p.UnitPrice);
                    TempData["TotalCostCheckout"] = totalCostCheckout.ToString();

                    _context.RemoveRange(basket.Items);
                    await _context.SaveChangesAsync();
                
                return RedirectToPage("/PlaceOrder");
            }
            return Page();

        }
    }
}

Webbshop/Pages/Confirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Webbshop.Pages
{
    public class ConfirmationModel : PageModel
    {
        public decimal TotalCost { get; set; }

        public void OnGet()
        {
            string totalCostString = TempData["TotalCost"] as string;

            TotalCost = decimal.Parse(totalCostString);
        }
    }

}

Webbshop/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Webbshop.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

Webbshop/Pages/FakeLogin.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Webbshop.Data;

namespace Webbshop.Pages
{
	public class FakeLoginModel : PageModel
	{
		private readonly AppDbContext database;
		private readonly IWebHostEnvironment environment;

		public FakeLoginModel(AppDbContext database, IWebHostEnvironment environment)
		{
			this.database = database;
			this.environment = environment;
		}

		// Log in as the user with the specified account ID, without providing a password etc.
		// IMPORTANT: This should only be allowed in development, hence the if statement below.
		public async Task<IActionResult> OnPost(int accountID)
		{
			if (!environment.IsDevelopment())
			{
				return Forbid();
			}

			// Find the account in the database.
			var account = database.Accounts.Find(accountID);
			string subject = account.OpenIDSubject;
			string issuer = account.OpenIDIssuer;
			string name = account.Name;

			// Create the fake identity and principal objects needed to fake a login.
			var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
			identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, subject, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
			identity.AddClaim(new Claim(ClaimTypes.Name, name, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
			var principal = new ClaimsPrincipal(identity);

			await HttpContext.SignInAsync(principal);

			return RedirectToPage("./Index");
		}
	}
}

Webbshop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Webbshop.Data;
using Webbshop.Models;

namespace Webbshop.Pages
{
	public class IndexModel : PageModel
	{
		private readonly AppDbContext database;

		public IndexModel(AppDbContext database)
		{
			this.database = database;
		}

		public List<Product> Products { get; set; } = new();
		public async Task OnGetAsync() =>
			Products = await database.Products.ToListAsync();
	}
}

Webbshop/Pages/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Webbshop.Data;
using Webbshop.Models;
using Microsoft.EntityFrameworkCore;

namespace Webbshop.Pages
{
    public class OrderModel : PageModel
    {
        private readonly AppDbContext context;
        private readonly IHttpContextAccessor httpContextAccessor;

        public OrderModel(AppDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            this.context = context;
            this.httpContextAccessor = httpContextAccessor;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public Product Product { get; set; }

        [BindProperty, Range(1, int.MaxValue, ErrorMessage = "You must order at least one item")]
        public int Quantity { get; set; } = 1;

        [BindProperty]
        public decimal Price { get; set; }

        public async Task OnGetAsync()
        {
            Product = await context.Products.FindAsync(Id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var accessControl = new AccessControl(context, httpContextAccessor);
                var accId = accessControl.GetLoggedInAccountId();

                var existingBasket = await context.Baskets 
                                     .Include(b => b.Items)
                                     .FirstOrDefaultAsync(b => b.AccountId == accId);

                Product = await context.Products.FindAsync(Id);
                Price = Product.Price;

                if (existingBasket != null)
                {
                    var existingItem = existingBasket.Items.Find(p => p.ProductId == Id);
                    if(existingItem != null)
                    {
                        existingItem.Quantity += Quantity;
                    }
                    else
                    {
                        existingBasket.Items.Add(new OrderItem
                        {
                            ProductId = Id,
                            UnitPrice = Price,
                            Quantity = Quantity,
                        });
                    }
                }
                else
                {
                    Basket basket = new()
                    {
                        AccountId = accId,
                        Items = new List<OrderItem>
                        {
                            new() {
                                ProductId = Id,
                                UnitPrice = Price,
                                Quantity = Quantity
                            }
                        }
                    };
                    context.Baskets.Add(basket);
                }

                await context.SaveChangesAsync();

                string confirmation = "The item has been added to your cart!";
                TempData["Confirmation"] = confirmation;

                decimal totalCost = Quantity * Price;
                TempData["TotalCost"] = totalCost.ToString();

                return RedirectToPage("/Confirmation");
            }
            Product = await context.Products.FindAsync(Id);
            return Page();
        }
    }
}

Webbshop/Pages/PlaceOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Webbshop.Pages
{
    public class PlaceOrderModel : PageModel
    {
        public decimal TotalCost { get; set; }
        public void OnGet()
        {
            string totalCostString = TempData["TotalCostCheckout"] as string;

            TotalCost = decimal.Parse(totalCostString);
        }
    }
}

Webbshop/Pages/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Webbshop.Data;
using Webbshop.Models;

namespace Webbshop.Pages
{
    public class SearchModel : PageModel
    {
        private readonly AppDbContext context;

        public SearchModel(AppDbContext context) => this.context = context;

        [BindProperty(SupportsGet = true)]
        public string Filter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Search { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? PageNum { get; set; }

        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public List<Product> Products { get; set; }

        public async Task<IActionResult> OnGetAsync(int? pageNum)
        {
            IQueryable<Product> products = context.Products;

            if (!string.IsNullOrEmpty(Search))
            {
                products = products.Where(p => p.Name.Contains(Search));
            }

            if (!string.IsNullOrEmpty(Filter))
            {
                products = products.Where(p => p.Category.Contains(Filter));
            }

            int totalProducts = products.Count();

            TotalPages = (int)Math.Ceiling((double)totalProducts / 10);

            CurrentPage = pageNum ?? 1;

            Products = products.Distinct().OrderBy(p => p.Category).ToList();

            Products = Products
                .Skip((CurrentPage - 1) * 10)
                .Take(10)
                .ToList();

            return Page();
        }
    }
}

Webbshop/Pages/Checkout.cshtml
@page
@model Webbshop.Pages.CheckoutModel
@{
    ViewData["Title"] = "Checkout";
}
<head>
    <link rel="stylesheet" href="/css/Checkout.css" />
</head>
<div class="main">
<div class="checkout-container container">
    <h1 class="title">Checkout</h1>
    @if (Model.basket != null && Model.basket.NumberOfItems > 0)
    {
            <table class="item">
                <thead>
                    <tr>
                        <th></th>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Cost per unit</th>
                        <th class="">Total</th>
                        <td colspan="5" class="delete">
                            <form method="post" asp-page-handler="RemoveAllItems">
                                <button type="submit">Delete All</button>
                            </form>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.basket.Items)
                    {
                        <tr>
                            <td>
                                <img src="/images/products/@Model.SelectedProducts.First(x => x.Id == item.ProductId).ImageName" alt="Product Image" />
                            </td>
                            <td>@Model.SelectedProducts.First(x => x.Id == item.ProductId).Name</td>
                            <td>@item.Quantity</td>
                            <td>@((item.UnitPrice).ToString("c"))</td>
                            <td class="">@((item.Quantity * item.UnitPrice).ToString("c"))</td>
                            <td class="delete">
                                <form method="post" asp-page-handler="RemoveProduct" asp-route-itemId="@item.Id">
                                    <button type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot class="total-price">
                    <tr>
                        <td colspan="5"><b>Total:</b></td>
                        <td class="">@Model.basket.Items.Sum(x => x.Quantity * x.UnitPrice).ToString("c")</td>
                    </tr>
                </tfoot>
            </table>
            <form method="post" style="display: flex; margin-top: 10px; justify-content: end">
                <button>Place order</button>
            </form>
    }
    else
    {
        <p>Your basket is currently empty</p>
    }
</div>
</div>

Webbshop/Pages/Confirmation.cshtml
@page
@model Webbshop.Pages.ConfirmationModel
@{
    ViewData["Title"] = "Item added";
    var confirmation = TempData["Confirmation"] as string;
}
<div class="container" style="margin-top: 10px">
    <p>@confirmation</p>
    <p>Total cost: @Model.TotalCost.ToString("c")</p>
    
</div>

Webbshop/Pages/FakeLogin.cshtml
@page
@model Webbshop.Pages.FakeLoginModel
@{
}

Webbshop/Pages/Index.cshtml
@page
@model IndexModel
@inject Webbshop.Data.AccessControl accessControl
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link rel="stylesheet" href="/css/index.css" />
</head>

<div class="container">
    <div>
        <h1>Welcome, @accessControl.GetLoggedInAccountName()!</h1>
        <div style="margin-top: 20px">
            <a style="margin-right: 20px" asp-page="/Search"><button>Search for a product</button></a>
            <a asp-page="/Checkout"><button>View cart</button></a>
        </div>
    </div>
</div>

Webbshop/Pages/Order.cshtml
@page "{id:int}"
@model Webbshop.Pages.OrderModel
@{
    ViewData["Title"] = "Place your order";
}
<head>
    <link rel="stylesheet" href="/css/order.css" />
</head>
<div class="main">
    <div class="container">
        <div class="left-column">
            <img class="" src="/images/products/@Model.Product.ImageName" title="@Model.Product.Name" />
        </div>

        <div class="right-column">
            <div class="product-desc">
                <h2>@Model.Product.Name</h2>
                <p>@Model.Product.Description</p>
            </div>

            <form class="order-form" method="post">
                <div class="product-price">
                    <label asp-for="Quantity" class="quantity-label"></label>
                    <input asp-for="Quantity" class="quantity-input" type="number" min="1" />
                    <span asp-validation-for="Quantity"></span>
                    <p>Unit cost: @(Model.Product.Price.ToString("c"))</p>
                    <button type="submit" class="submit-btn">Place order</button>
                </div>
            </form>
        </div>

    </div>
</div>

Webbshop/Pages/PlaceOrder.cshtml
@page
@model Webbshop.Pages.PlaceOrderModel
@{
    ViewData["Title"] = "Confirmation";
}

<div class="container" style="margin-top: 10px">
    <p>Your order has been placed successfully!</p>
    <p>Total cost: @Model.TotalCost.ToString("c")</p>
</div>

Webbshop/Pages/Search.cshtml
@page
@model Webbshop.Pages.SearchModel
@{
    ViewData["Title"] = "Search";
}
<head>
    <link rel="stylesheet" href="/css/Search.css" />
</head>

<div class="container">
    <form style="display: flex; align-items:center; justify-content: space-between;" method="get">
        <div class="form-container">
            <input asp-for="Search" id="searchString" type="search" placeholder="Search" />
            <div>
                <button type="submit" class="search-btn">Search</button>
            </div>
        </div>
        <div class="form-container" style="margin-right: 10px">
            <label for="filter">Filter:</label>
            <select asp-for="Filter" id="filter">
                <option value="">All</option>
                <option value="Kläder">Kläder</option>
                <option value="Accessoarer">Accessoarer</option>
                <option value="Mat och dryck">Mat och dryck</option>
                <option value="Elektronik">Elektronik</option>
                <option value="Hem och trädgård">Hem och trädgård</option>
                <option value="Sport och fritid">Sport och fritid</option>
                <option value="Utomhus">Utomhus</option>
            </select>
            <div>
                <button type="submit" class="search-btn">Filter</button>
            </div>
        </div>
    </form>
</div>

<div class="container products">
    @foreach (var product in Model.Products)
    {
        <div class="container-product">
            <div class="container-card">
                <a asp-page="/Order" asp-route-id="@product.Id">
                    <div class="container-img">
                        <img src="/images/products/@product.ImageName" alt="@product.ImageName" />
                    </div>
                    <div class="card-body">
                        <h2 class="card-title">@product.Name</h2>
                        <p class="card-desc">@product.Description</p>
                        <div class="bot-info">
                            <span>@(product.Price.ToString("c"))</span>
                            <a asp-page="/Order" asp-route-id="@product.Id"><button>Order Now</button></a>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

<div class="container" style="padding-top: 10px; margin-bottom: 10px">
    <div class="page-btns">
        @if (Model.TotalPages > 1)
        {    
            <div style="display: flex">
                @if (Model.CurrentPage > 1)
                {
                    <div style="margin-right: 30px">
                        <a asp-page="/Search" asp-route-pageNum="1" asp-route-search="@Model.Search" asp-route-filter="@Model.Filter" class="page-link">
                            <button class="page-btn"><i class="fa-solid fa-angles-left"></i></button>
                            </a>
                        <a asp-page="/Search" asp-route-pageNum="@(Model.CurrentPage - 1)" asp-route-search="@Model.Search" asp-route-filter="@Model.Filter" class="page-link">
                            <button class="page-btn"><i class="fa-solid fa-angle-left"></i></button>
                            </a>
                    </div>
                }

                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <div>
                        <a asp-page="/Search" asp-route-pageNum="@(Model.CurrentPage + 1)" asp-route-search="@Model.Search" asp-route-filter="@Model.Filter" class="page-link">
                            <button class="page-btn"><i class="fa-solid fa-angle-right"></i></button>
                        </a>
                        <a asp-page="/Search" asp-route-pageNum="@Model.TotalPages" asp-route-search="@Model.Search" asp-route-filter="@Model.Filter" class="page-link">
                            <button class="page-btn"><i class="fa-solid fa-angles-right"></i></button>
                            </a>
                    </div>
                }
            </div>
        }
        <span>Page @Model.CurrentPage of @Model.TotalPages</span>
    </div>
</div>